import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/navbar";
import { Outfit } from "next/font/google";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
