import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./component/navbar";
import { Outfit } from "next/font/google";
import { Analytics } from "@vercel/analytics/next";
import FooterComp from "./component/footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
    icons:{
    icon: "/iconMuni.svg",
  },
};
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['100', '400', '700'],
});
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased`}
        style={{background:'linear-gradient(0deg, rgba(44, 51, 40, 1.000) 0.000%, rgba(0, 0, 0, 1.000) 50.000%, rgba(0, 0, 0, 1.000) 100.000%)'}}
      >
        <Navbar/>
        {children}
        <Analytics/>
        <FooterComp/>
      </body>
    </html>
  );
}
